name: flutter_final_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_it: ^7.6.4
  go_router: ^13.0.0
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.2
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
